### ISSUE TITLE
What does it do??

### ISSUE THREAD

**Issue by forresto** [flowbased/fbp-loader#1]
Needs more README :)

**Comment by chadrik** [comment]
Seems like this could just be part of the fbp repo.  is there a reason to keep it separate?

**Comment by bergie** [comment]
@chadrik I'm following the naming convention of Webpack loaders here, which have NPM modules named `<ext>-loader`. For example: [coffee-loader](https://github.com/webpack/coffee-loader) or [json-loader](https://github.com/webpack/json-loader)

@forresto sure, will add a readme!
